// export const FETCH_USER = 'FETCH_USER';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_SESSION_ERRORS =  'RECEIVE_SESSION_ERRORS';
export const RECEIVE_CHANNELS = 'RECEIVE_CHANNELS';
export const RECEIVE_CHANNELS_ERRORS = "RECEIVE_CHANNELS_ERRORS";
